name: Update Jekyll Site from Google Drive

on:
  schedule:
    - cron: '0 0 * * *'  # This runs the workflow daily
  push:
    branches:
      - master  # Trigger on pushes to the main branch

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Google Credentials
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS }}" > $HOME/service-account.json
          export GOOGLE_APPLICATION_CREDENTIALS=$HOME/service-account.json

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby-full
          gem install bundler jekyll
          pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib

      - name: Sync Files from Google Drive
        run: python scripts/sync_files.py

      - name: Build Jekyll Site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESSTOKEN }}
          publish_dir: _site
